# Generated by Django 6.1.1 on 2026-09-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Collections', 'Collections'), ('Sale', 'Sale')], default='Men', max_length=50),
        ),
    ]
